# 使用 nvidia/cuda 基础镜像
FROM nvidia/cuda:13.0.1-cudnn-runtime-ubuntu24.04
# 设置环境变量
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Shanghai\
    PYTHON_VERSION=3.13 \
    UV_VERSION=latest
# # 使用清华大学的apt源
# RUN sed -i 's/http:\/\/archive.ubuntu.com/http:\/\/mirrors.tuna.tsinghua.edu.cn\/ubuntu/g' /etc/apt/sources.list

# 安装基础依赖并清理缓存
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# 安装 uv (Python 包管理器)
RUN echo "开始安装 uv..." && \
    curl -fsSL https://astral.sh/uv/install.sh | sh
RUN echo "安装完成，移动二进制文件..." && \
    mv ~/.local/bin/uv /usr/local/bin/&& \
    echo "验证安装..." && \
    uv --version || (echo "uv 安装失败" && exit 1)
# # 使用 uv 安装指定 Python 版本
# RUN uv venv --python python${PYTHON_VERSION} /opt/venv
# 复制 pyproject.toml 到 app
# uv pip install vllm --torch-backend auto
COPY pyproject.toml /app/
# 配置开发环境
WORKDIR /app
# 创建并激活虚拟环境
RUN uv sync
EXPOSE 8600
# 字符集
ENV LANG C.UTF-8
CMD ["vllm", "serve", "Qwen/Qwen3-0.6B"]